### ISSUE TITLE
Generative Adversarial Networks for Image-to-Image Translation on Multi-Contrast MR Images - A Comparison of CycleGAN and UNIT

### ISSUE THREAD

**Issue by HYUNMIN-HWANG** [yskim0/One-Day-One-Paper#13]
# GENERATIVE ADVERSARIAL NETWORKS FOR IMAGE-TO-IMAGE TRANSLATION ON MULTI-CONTRAST MR IMAGES - A COMPARISON OF CYCLEGAN AND UNIT
- https://arxiv.org/abs/1806.07777
- Github : https://github.com/simontomaskarlsson/GAN-MRI
- [Submitted on 20 Jun 2018]

--- 

## Summary 
그동안 데이터 증강을 하기 위한 여러 시도들이 있었고, 해당 논문에서는 MR이미지를 기반으로 어떤 GAN 모델이 좋은지 CycleGAN 과 UNIT을 비교, 분석했다.
(we evaluate two unsupervised GAN models (CycleGAN and UNIT) for image-to-image translation of T1- and T2-weighted MR images, by comparing generated synthetic MR images to ground truth images.)

## Method
- CycleGAN_s : CycleGAN에 MAE 지표를 추가하여 모델이 최소 MAE 성과를 보이기 위해 훈련할 수 있도록 했다.
- Generator_s : CycleGAN에서 generator 부분만 사용함 (cyclic loss 없음)
- T1이미지를 input -> T2이미지를 output (vice versa)
- MAE 지표를 비교해 T1-과 T2- 에서 어떤 GAN 모델의 성능이 좋은지 평가한다. (추가로 mu-tual information (MI), and peak signal to noise ratio (PSNR)도 지표로 사용함)
- 그 후, 사람이 직접 보고 무엇이 합성한 사진인 것 같은지 평가하는 방식도 함 (perceptual study)

## Result
![image](https://user-images.githubusercontent.com/70581043/127760103-917c0ccb-791c-4f77-83d4-d7edfca5013a.png)
- Generator_s 성능이 가장 좋다.
- CycleGAN_s가 CycleGAN보다 T2에서의 성능이 더 좋다.
- CycleGAN와 UNIT 성능 유사함

![image](https://user-images.githubusercontent.com/70581043/127760183-fb4f42cc-90d2-45c8-ac3c-ede4fd43dfad.png)
- T2 이미지는 T1 이미지에 비해 사람이 눈으로 분석하기 어렵다. (더 어두움)
- 만약 최소 MAE를 목표로 하는 게 아닌, 사실적인 이미지 만들기가 목표로 잡고 훈련을 시켰다면 결과가 달라질 수 있을 것이라 예상
- 하지만 'assessing how realistic an image is' 지표를 만드는 게 어렵다.

---
+  UNIT 뭔지 조사 ⛳
+  'assessing how realistic an image is' 지표로 만들어진 것이 있는지 조사 ⛳

**Comment by yskim0** [comment]
| 'assessing how realistic an image is' 지표로 만들어진 것이 있는지 조사 ⛳
-> 이 부분은 GAN 지표 보시면 도움 되실 것 같아요! 허점이 많은 편이지만 그래도 정량적인 면에서는 쓰이니까요 FID, IS 종종 봤어요

GAN쪽은 제가 예전에 관심을 많이 가지고 공부했었는데 거기에 의료 도메인에 쓰이는 걸 보니 더 재밌게 보이네요 ㅎㅎ

**Comment by HYUNMIN-HWANG** [comment]
@yskim0 감사합니다 !!! 말씀해주신 GAN 지표들 공부해봐야겠어요 😀
