### ISSUE TITLE
Artificial Intelligence in Ovarian Cancer Diagnosis

### ISSUE THREAD

**Issue by ghuijo** [yskim0/One-Day-One-Paper#14]
## Abstract
**_Use artificial intelligence (AI) to predict the pathological diagnosis of ovarian tumors using patient information and data from preoperative examinations_**
* 5 machine learning classifiers 사용함.
  > support vector machine
  random forest
  naive Bayes
  logistic regression
  XGBoost
* blood tests, patient background, and imaging tests 등에서 뽑은 16개의 features 사용함.
* 가장 높은 정확도가 XGBoost 알고리즘에서 0.80 나옴.
* ovarian tumor의 경우, 수술적 방법 외에는 정확한 진단이 어려우므로, medical 정보를 이용해 ai로 예측하는 것이 필요함.
* 전체 202명의 환자 데이터 사용
  > 53 with ovarian cancer
  23 with borderline malignant tumors
 126 with benign ovarian tumors.

## Methods
* The 202 cases were randomly assigned to the “training” (70%) or “test” data (30%) through a random number generator.
* 정확도 측정 방법
  > (Accuracy)=(Correctly predicted as benign case in benign tumors)+(Correctly predicted as borderline tumor case in borderline tumors)+(Correctly predicted as ovarian cancer in ovarian cancers)/Total cases
* 5개의 machine learning algorithm을 정확히 어떻게 적용했는지는 안 나옴.
* features 간에 중요하게 나온 것을 파악함.
  > ovarian cancer group에서 median CA125가 가장 높았음.
  borderline tumor group에서 median CA19-9와 CEA levels이 가장 높았음.

##
* 쓰인 feature 참고 (유의미하다고 머신이 돌려서 나온 건 아니고 그냥 사람이 고른 거)
<image src="https://user-images.githubusercontent.com/67627471/127763053-e81796ff-2dab-4ccd-a6de-75b72efcf569.png" width="70%" height="70%" />

##
* 아직 진단 분야에는 deep learning 연구가 드물어서 machine learning 연구 논문을 봤는데 정확도가 역시 낮은 듯..
* feature range가 다 다른데 어떻게 normalization했는지 안 나옴.
* 저자가 AI 전문이 아니고 완전 medical 쪽인 듯.
* 혹시 medical test data 바탕으로 deep learning based diagnosis하는 연구 논문 좋은 거 아시는 분 계시나요..? medical image는 꽤 있는데 이쪽은 정말 찾기 어렵네요..

**Comment by HYUNMIN-HWANG** [comment]
아직 안 읽어봐서 좋은 논문이 있는지는 모르겠지만... 요즘에 COVID 19 diagnosis (chest xray) 관련해서 많이 나오는 것 같아요 !

**Comment by ghuijo** [comment]
@HYUNMIN-HWANG 감사합니다~! chest xray면 병변 detection이나 segmentation 쪽으로 흥미로운 논문이 많겠어요!
