### ISSUE TITLE
A Study of Fandom Index based on Social Media Data Analysis

### ISSUE THREAD

**Issue by kimsook** [yskim0/One-Day-One-Paper#149]
# 소셜미디어 데이터 분석을 통한 팬덤 지표 연구
- 한국디지털콘텐츠학회 논문지. 2019-12 20(6):1257-1265

### Abstract
- 특정 그룹의 팬덤 규모를 가늠하는 지표
- = 팬덤 내 존재하는 팬덤 리더를 팔로우하는 총 볼륨
- 트위터 내에 존재하는 팬덤 문화 양상에 주목하여, 해당 문화를 주도하는 팬덤 리더를 찾고 이를 팔로우하는 총 사용자 수를 팬덤 지표로 제시
- 상시측정이 가능하면서도 음반판매량 지표와 부합하는 유의미한 지표임을 실험으로 확인
- 기존 지표인 음반 판매량의 한계
    - 월별로 공개 -> 상시 측정 불가능
    - 발매 시점에 종속되는 수치
    - 시간 변수를 통제해야 팬덤의 척도로 비교할 수 있음
- 팬덤 리더
    - 팬덤 구성원이 공유하는 텍스트보다 더 양질의 텍스트를 공유하는 페르소나
    - 텍스트 ‘생산자’로의 역할을 수행
    - 페르소나에서 다른 트위터 사용자와의 유대감을 형성하거나 다른 사용자의 텍스트를 본인들의 피드에 노출하지 않음
![image](https://user-images.githubusercontent.com/40443049/133439528-742c1806-8cb1-4b13-8725-6573c49af582.png)
![image](https://user-images.githubusercontent.com/40443049/133439663-333c13d7-dcce-4592-8ae3-2758f435c7cb.png)
- 새로운 지표 '팬덤 리더 팔로워 볼륨'
    - 전체 팬덤 지표 = 각 팬덤 내 존재하는 팬덤 리더를 팔로우하는 총 볼륨
    - 팬덤 리더들의 팔로워 수를 수집 -> 팬덤 별 각 팬덤 리더들의 팔로워 수 총합
- 음반판매량과 제안한 팬덤 지표의 차이에 대한 비모수검정(Wilcoxon Rank-sum test)
    - p-value = 0.8335, 유의수준 0.05에서 귀무가설을 기각X
    - 음반판매량과 팬덤 지표의 분포는 동일 
    - 유의미한 팬덤 지표임

**Comment by yskim0** [comment]
헐 이건 진짜 융콘 재질이네요 !! 재밌어보인다
