### ISSUE TITLE
A Study on Personalized Music Recommendation Model through Analysis on Users' Music Preference Factors

### ISSUE THREAD

**Issue by kimsook** [yskim0/One-Day-One-Paper#150]
# 사용자의 음악 선호요인 분석을 통한 개인 맞춤형 음악추천모델 연구
- 한국디지털콘텐츠학회 논문지. 2018-12 19(11):2041-2047

### Abstract 
- 기존 음악 추천 시스템: 청취 기록 등 사용자 데이터를 근거로 추천
- 음악적 분석 데이터를 활용 -> 음악요서에 따라 개인별 음악 선인지여부와 선호여부를 통해 사용자의 선호경향을 파악 -> 선형 회귀 분석을 통해 개인화된 음악추천모델 제안
- 즉, 음악요소 데이터와 개인의 선호여부를 통해 음악 선호 요인 도출
- 예측 정확도: 84.4%

> 최근 5년간 연간 100위권 내에 진입한 총 460곡의 대중가요를 음악적 분석을 통해 대중음악의 전반적인 동향과 일반적인 선호 경향을 분류
- 독립변수 k개에 대한 선형관계
![image](https://user-images.githubusercontent.com/40443049/133544792-4a8b0e46-fc56-4577-a9aa-6f3aaebb0dad.png)
![image](https://user-images.githubusercontent.com/40443049/133544889-f399bfb5-237c-49e9-887f-c3b36a0e9804.png)
![image](https://user-images.githubusercontent.com/40443049/133544940-e2a30621-6b11-4a23-be04-395eb5ee5dd6.png)
- 실험 참가자 20명의 실험을 통해 음악의 선호도 여부 조사
- 개인화된 추천 곡의 선곡 과정
- 검증 단계에서 개인화된 추천 곡을 다음과 같이 선별
    - 훈련 단계 실험에서 나타난 선호 곡 예측 정확도를 통해 선호 요소별 파라미터 값의 가중치 계산
    - 훈련 단계 실험에서 나타난 가중치를 실험하지 않은 곡의 파라미터 값에 적용
    - 파라미터값이 높은 순으로 좋아하는 곡 선별
    - 파라미터값이 음수값에서 높은 순으로 싫어하는 곡 선별
    - 좋아하는 곡 70%와 싫어하는 곡 30%의 비율로 예측
![image](https://user-images.githubusercontent.com/40443049/133545436-222d24ae-d9ab-4cfb-be9b-1829b58a53b9.png)
![image](https://user-images.githubusercontent.com/40443049/133545593-bb0d6b3d-d893-423a-b44a-6e635b298ce3.png)

**Comment by yskim0** [comment]
재밌어보여요! 저도 이런 비즈니스 관련된 머신러닝/딥러닝 논문들 자주 보고 싶네요 ㅎㅎ 언니를 통해 보겠습니다.......
