### ISSUE TITLE
💸 벌금 관리 장부 8/6 ~ 8/12

### ISSUE THREAD

**Issue by HYUNMIN-HWANG** [yskim0/One-Day-One-Paper#29]
## 8/6 ~ 8/12
|날짜|김연수|황현민|이미경|조건희|김희숙|
|:---:|:---:|:---:|:---:|:---:|:---:|
|지난주|18000|20000|16000|20000|19000|
|8/6|-|-|-|-|-|
|8/7|🏖|-|-|-|-|
|8/8|❌|-|❌|-|🏖|
|8/9|-|-|🏖|🏖|-|
|8/10|-|-|-|-|-|
|8/11|-|-|-|-|-|
|8/12|✖|🏖|-|-|-|
|벌금|3000|0|2000|0|0| 
|남은 보증금|15000|20000|14000|20000|19000|

`총 벌금` : ₩5000 
현민, 건희, 희숙님 공동 1등으로 1,666원씩 나눔

**Comment by HYUNMIN-HWANG** [comment]
🏖 : 휴식
✖ : 지각
❌ : 결석 
- : 완료

**Comment by yskim0** [comment]
8/12 김연수 지각입니다~
