### ISSUE TITLE
Rethinking the Inception Architecture for Computer Vision

### ISSUE THREAD

**Issue by leemik3** [yskim0/One-Day-One-Paper#31]
# Rethinking the Inception Architecture for Computer Vision
- Szegedy, Christian, et al. "Rethinking the inception architecture for computer vision." Proceedings of the IEEE conference on computer vision and pattern recognition. 2016.
- link : arxiv.org/pdf/1512.00567v3.pdf
---
Inception 구조의 복잡성 때문에 네트워크를 바꾸는 것이 어렵다.
해당 논문에서는 합성곱 신경망을 효율적으로 **scale up** 할 수 있는 아이디어를 제시함

### Factorizing Convolutions with Large Filter Size
1. Factorization into smaller convolution
큰 필터 사이즈를 갖는 합성곱은 더 작은 합성곱으로 바꿔주는 것이 정확도 면에서도 좋고 파라미터 수도 줄어든다. 

2. Spatial Factorization into a Asymmetric Convolutions
nXn convolution은 (n-1)X(n-1) convolution으로 변환하는 것보다 nx1, 1xn convolution으로 변환하는 것이 더 효과가 좋음, n이 커질 수록 연산 비용 절약량이 더욱 커짐. 
다만 early layer에서는 잘 작동하지 않고, medium grid size(12~20)에서 효과가 좋았음

### Utility of Auxiliary Classifiers
Auxiliary classifier는 성능 향상의 효과보다는 **정규화**의 효과가 좋음

### Efficient Grid Size Reduction
기존 : feature map의 사이즈를 줄이기 위해서 pooling 연산을 사용 + representational bottleneck 현상을 피하기 위해서 필터 수는 늘렸다.
--> 이렇게 하면 연산량은 줄어들지만(good) **신경망의 표현력**도 감소한다(bad).

해결 방안 : 
![img](https://user-images.githubusercontent.com/57309696/128472315-8a054bac-9a17-470d-a947-0c8ca40deaae.PNG)

### Model Regularization via Label Smoothing

**Comment by yskim0** [comment]
👍👍👍👍
