### ISSUE TITLE
Subway Congestion Prediction and Recommendation System using Big Data Analysis

### ISSUE THREAD

**Issue by kimsook** [yskim0/One-Day-One-Paper#42]
# 빅데이터 분석을 이용한 지하철 혼잡도 예측 및 추천시스템
- Journal of digital convergence v.14 no.11 , 2016년, pp.289 - 295  

### Abstract
- 기존 지하철 혼잡도를 다중 회귀 분석으로 예측함
- 빅데이터 처리를 통해 실시간으로 혼잡도 모니터링, 자신의 출발역과 도착역 정보와 개인화된 혼잡도 예측 시스템을 제안함
- 예측 혼잡도는 실제 혼잡도에 비해 평균 81% 정확도를 보임

### 혼잡도 지표
- 지하철의 경우 환승게이트 없이 환승하므로 역의 승하차 인원만으로 혼잡도를 정확히 예측하기 어려움
- 현재 사용하는 혼잡도 측정은 목측 방법과 설정된 경로 데이터를 활용하여 추정하는 것이 전부
- 인천교통사에서 사용하는 혼잡도 산정 기준(1) 
![image](https://user-images.githubusercontent.com/40443049/128707573-8e3fb5a0-5eb9-443d-b79e-41c6f296e981.png)
- Passengers = 총 재차인원 = 좌석인원과 입석인원의 총합, Capacity = 차량 정원
- 혼합도 추정 조건
![image](https://user-images.githubusercontent.com/40443049/128707742-10ca2762-148b-467b-b833-38fc3a31da70.png)

### 사용한 데이터
- 2013-2014 지하철 통계자료
- 플랫폼의 계단, 장애인 및 노약자용 엘리베이터 등의 위치 정보, 차량의 칸번호, 문번호와의 최단거리 매칭 데이터베이스 구축
- 국제업무지구방향의 첨두시간에 측정된 데이터
![image](https://user-images.githubusercontent.com/40443049/128709117-2aa630a7-81dc-4a02-b2b4-1eec09c46e77.png)
- 독립변수: In Passenger, Out Passenger, Income, BigData, Transit Stop, Bus, Bus/Subway, wait time, Building
- 종속변수: Congestion

### 다중회귀분석
- 두 개 이상의 독립 변수들에 대한 종속 변수인 다른 변수들 사이의 결합 분포인 함수 관계를 수학적 모형을 통해 표현하여 인과관계를 분석하는 것
- 즉, 독립변수들의 변화에 따른 종속 변수의 변화를 예측하는 통계 기법
- 독립변수가 k개인 선형 회귀 모형(2)
![image](https://user-images.githubusercontent.com/40443049/128708974-0589e6e9-8220-4a10-a67e-847aa5374b3a.png)

### 다중회귀분석 결과
![image](https://user-images.githubusercontent.com/40443049/128709668-1d68a19d-3ad9-4346-b988-e93bebc04e77.png)

### 혼잡도 계산 수식
![image](https://user-images.githubusercontent.com/40443049/128709846-a5e57909-d66c-450f-9531-d30fae6ab528.png)
- i = 현재역, i-1 = 이전역, CIi-1 = 이전역의 혼잡도, 알파(i)/베타(i) = 현재역의 승/하차 인원, T = 환승역, N = 차량 정원

### 결론
![image](https://user-images.githubusercontent.com/40443049/128710234-70ae117f-834a-4b90-a0e5-f9edf30aae30.png)
- 예측 혼잡도의 정확도 : 81%
- 특정 환승역과 같은 대규모 중심역 방향쪽의 역들은 낮은 예측도에 비해 혼잡도가 증가하는 등 이러한 혼잡도 예측의 오류를 보정하기 위해 중심역 방향에 가까울수록 혼잡도 가중치를 적용해야함

**Comment by yskim0** [comment]
헐 이거 너무 신기해요
